[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[build.buildCommand]]
cmd = "npm ci"

[[build.buildCommand]]  
cmd = "npx prisma generate"

[[build.buildCommand]]
cmd = "npm run build"

[build.watchPatterns]
include = ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.json"]
ignore = ["node_modules/**", ".next/**", "dist/**"]